= Dictée de Mérimée

:1: https://fr.wikipedia.org/wiki/Dictée_de_Mérimée

La {1}[dictée de Mérimée] fut écrite et dictée en 1857 par Prosper Mérimée à la demande de
l’impératrice Eugénie afin de distraire la cour.

== Orthographe standard

« Pour parler sans ambiguïté, ce dîner à Sainte-Adresse, près du Havre, malgré
les effluves embaumés de la mer, malgré les vins de très bons crus, les
cuisseaux de veau et les cuissots de chevreuil prodigués par l’amphitryon, fut
un vrai guêpier.

Quelles que soient, et quelque exiguës qu’aient pu paraître, à côté de la somme
due, les arrhes qu’étaient censés avoir données la douairière et le marguillier,
il était infâme d’en vouloir pour cela à ces fusiliers jumeaux et mal bâtis, et
de leur infliger une raclée, alors qu’ils ne songeaient qu’à prendre des
rafraîchissements avec leurs coreligionnaires.

Quoi qu’il en soit, c’est bien à tort que la douairière, par un contresens
exorbitant, s’est laissé entraîner à prendre un râteau et qu’elle s’est crue
obligée de frapper l’exigeant marguillier sur son omoplate vieillie.  Deux
alvéoles furent brisés ; une dysenterie se déclara suivie d’une phtisie, et
l’imbécillité du malheureux s’accrut.

— Par saint Martin ! quelle hémorragie ! s’écria ce bélître.

À cet événement, saisissant son goupillon, ridicule excédent de bagage, il la
poursuivit dans l’église tout entière. »

== Alphabet Phonétique International

puʁ paʁlˈe sɑ̃z ɑ̃biɡyitˈe
sə- dinˈe a sˈɛ̃tadʁˈɛs
pʁɛ dy- ˈavʁ
malɡʁˈe le-z eflˈyvz ɑ̃bomˈe də- la- mˈɛʁ
malɡʁˈe le- vˈɛ̃ də- tʁɛ bˈɔ̃ kʁˈy
le- kyisˈo də- vˈo e le- kyisˈo də- ʃəvʁˈœj pʁɔdiɡˈe paʁ lɑ̃fitʁiˈɔ̃
fˈy œ̃ vʁˈɛ ɡɛpjˈe

kɛl kə swˈa
e kˌɛlkə ɛɡziɡˈy kɛ pˈy paʁˈɛtʁ
a kotˈe də- la- sˈɔm dˈy
le-z ˈaʁ ketˈɛ sɑ̃sˈez avwˈaʁ dɔnˈe la- duɛʁjˈɛʁ e lə- maʁɡijjˈe
il etˈɛt ɛ̃fˈaːm dɑ̃ vulwˈaʁ puʁ səlˌa a se fyziljˈe ʒymˈoz e mˈal batˈi
e də- lœʁ ɛ̃fliʒˈe yn ʁaklˈe
alˌɔʁ kil nə- sɔ̃ʒˈɛ ka pʁˈɑ̃dʁ de- ʁafʁɛʃismˈɑ̃ avˌɛk lœʁ kɔʁəliʒjɔnˈɛʁ

kwˌa kil ɑ̃ swˈa
sɛ bjˈɛ̃n a tˈɔʁ kə la- duɛʁjˈɛʁ
paʁ œ̃ kɔ̃tʁəzˈɛnz ɛɡzɔʁbitˈɑ̃
sɛ lɛsˈe ɑ̃tʁɛnˈe a pʁˈɑ̃dʁ œ̃ ʁatˈo
e kɛl sɛ kʁˈy ɔbliʒˈe də- fʁapˈe lɛɡziʒˈɑ̃ maʁɡijjˈe syʁ sɔ̃n ɔmɔplˈat vjɛjˈi
dˈøz alveˈɔl fyʁ bʁizˈe
yn dizɑ̃tʁˈi sə- deklaʁˈa syivˈi dyn ftizˈi
e lɛ̃besilitˈe dy- maløʁˈø sakʁˈy

paʁ sˈɛ̃ maʁtˈɛ̃
kɛl emɔʁaʒˈi
sekʁiˈa sə- belˈitʁ

a sɛt evenmˈɑ̃
sɛzisˈɑ̃ sɔ̃ ɡupijˈɔ̃
ʁidikˈyl ɛksedˈɑ̃ də- baɡˈaʒ
il la- puʁsyivˈi dɑ̃ leɡlˈiz tut ɑ̃tjˈɛʁ

== Akarlãg

« Půr parlé sã z'ãbiguité, se diné a Sĩt-Adrès, pré du Avr, malgré lé z'éfluv'
z'ãbômé' de la mèr, malgré lé vĩ' de trè bõ cru', lé kuisô' de vô é lé kuisô' de
cevrœy prodigé' par l'ãfitriõ, fu t'ũ vrè gèpyé.

kèl' ke swa, é kèlk éẍigu' k'è' pu parètr, a kôté de la som du, lé z'ar'
k'étè' sãsé' avwar doné' la důèryèr é le margiyé, il étè t'ĩfam d'ã vůlwar půr
sela a sé fuziyé' jumô' z'é mal bâti' é de lœr ĩflijé un raklé, alor k'il' ne
sõjè' k'a prãdr dé rafrècismã' avèk lœr korelijionèr'.

kwa k'il ã swa, s'è byũ n'a tor ke la důèryèr, par ũ kontresãs èẍorbitã, s'è
lèsé ãtrèné a prãdr ũ râtô é k'èl s'è kru oblijé de frapé l'èẍijã margiyé sur sõ
n'omoplat vyèyi. Dœ z'alvéol' fur' brizé' ; un dizãtri se déklara suivi d'un
ftizi, é l'ĩbésilité du malœrœ s'akru.

— Par sĩ Martĩ ! Kel émoraji ! » s'ékria se bélitr.

A sèt événmã, sèzisã sõ gůpiyõ, ridikul èxédã de bagaj, il la půrsuivi dã
l'égliz tůt ãtyèr. »

== Akarlahg

« Phur parleh sah z'ahbiguiteh, se dineh a Siht-Adrhes, prhe du Avr, malgreh leh
z'ehfluv' z'ahbomeh' de la mher, malgreh leh vih' de trhe boh cru', leh kuiso' de
vo eh leh kuiso' de cevrey prodigeh' par l'ahfitrioh, fu t'uh vrhe ghepyeh.

khel' ke swa', eh khelk hegzigu' k'he' pu parhetr, a koteh de la som du, leh z'ar'
k'ehthe' sahseh' avwar doneh' la dhuheryher eh le margiyeh, il ehthe t'ihfam d'ah
vhulwar phur sela a seh fuziyeh' jumo' z'eh mal bati' eh de ler ihflijeh un
rakleh, alor k'il' ne sohjhe' k'a prahdr deh rafrhecismah' avhek ler
korelijionher'.

kwa k'il ah swa, s'he byuh n'a tor ke la dhuheryher, par uh kohtresahs
hegzorbitah, s'he lheseh ahtrheneh a prahdr uh rato eh k'hel s'he kru oblijeh de
frapeh l'hegzijah margiyeh sur soh n'omoplat vyheyi. De z'alvehol' fur' brizeh' ;
un dizahtri se dehklara suivi d'un ftizi, eh l'ihbehsiliteh du malere s'akru.

— Par sih Martih ! Kel ehmoraji ! » s'ehkria se behlitr.

A shet ehvehnmah, shezisah soh ghupiyoh, ridikul heksehdah de bagaj, il la
phursuivi dah l'ehgliz thut ahtyher. »

== Alfonic

« pwr parle sä z-äbiguite, sx dine a së t-adrès, pre du avr, malgre le z-efluv
äbome dx la mèr, malgre le vë dx tre bö cru, le cuiso dx vo e le cuiso dx hxvrxy
prodige par l äfitriyö, fu t-ë vre gepie.

cel ce swa, celc egzigu c è pu parètr, a cote dx la som du, le z-ar c etè säse
avwar done la dwèrièr e lx margiye, il etè infam d ä vwlwar, pwr sxla, a se
fuzilie jumo e malbati, e dx lxr ëflije un racle, alor c il nx söjè c a prädr de
rafrèhismä avèc lxr corxlijionèr. cwa c il ä swa, s e bië n-a tor cx la dwèrièr,
par ẍ cötrxsäs egzorbitä, s e lese ätrene a prädr ẍ rato e c èl s e cru oblije
dx frape l egzijä margiye sur sö n-omoplatx vieyi. dx z-alveol fur brize ; unx
dizätri sx declara suivi d unx ftizi e l ëbesilite du malxrx s acru.

— par së t-ipolit, cel emoraji ! » s ecria sx belitr.

a set evènmä, sezisä sö gwpiyö, ridicul ecsedä dx bagaj, il la pwrsui dä l egliz
tw t-ätièr. »

== Ortofasil /Fonétik

« Pör parlé sã ãbiguité, se diné a sĩt-adrès, prè du Havr, malgré léz éfluv
ãbomé de la mèr, malgré léz vĩ de trè bõ kru, lé kuiso de vo é lé cuissots de
cevrëy prodigé par l’ãfitriyõ, fu ũ vrè gépyé.

Kèl ke swa, é kèlke ègzigu k’è pu parètr, a koté de la som du, léz ar k’étè
sãséz avwar doné la dwèryèr é le margiyé, il étè ĩfam d’ã völwar pör sela a sé
fuzilyé jumeaux é mal bati, é de lër ĩflijé un raklé, alor k’il ne sõjè k’a
prãdr dé rafrécismã avèk lër korelijyonèr. Kwa k’il ã swa, s’è byĩn a tor ke la
dwèryèr, par ũ kõtresãs ègzorbitã, s’è lèsé ãtrèné a prãdr ũ rato é k’èl s’è kru
oblijé de frapé l’ègzijã margiyé sur sõn omoplat vyéyi. Dez alvéol fur brizé ;
un disãtri se déklara suivi d’un ftizi, é l’ĩbésilité du malere s’akru.

— Par sĩ Martin ! kèl émoraji ! s’ékriya se bélitr.

A sèt évènmã, sézisã sõ göpiyõ, ridikul èksédã de bagaj, il la pörsuivi dã
l’égliz töt ãtyèr. »
