= Le Maharadjah est l'ami du Shah

> Que les lecteurs fâchés avec l'orthographe se rassurent, car, même si les
dictionnaires semblent rarement d'accord, toutes ces graphies sont possibles. Et
bien d'autres mots peuvent s'orthographier de deux façons. D'où les deux dictées
suivantes, aussi recevables l'une que l'autre.

Extrait du « Dictionnaire amoureux de la Langue française » de Jean-Loup Chiflet

== Orthographe standard — version 1

Ami du **chah**, le **maharajah**, sitôt sorti de l'**ashram**, courut retrouver dans l'arrière-salle d'un **bistro** le **guru** et un **muphti** de ses amis.
Étaient aussi présents un **calife** **irakien**, de **Bagdad** pour être précis, et un **Cingalais**, pêcheur à Puttalam et vêtu d'un **chantoung** coloré.
Tous conversaient paisiblement autour d'un **narguilé** chargé de **haschisch** parfumé à l'huile de coprah.
La curieuse confrérie ne tarda pas à divaguer, non loin de beaux **lis** et jolis bougainvilliers.
Le **muphti**, qui était un grand **soufi**, entama une **sourate** et des soutra qui n'amusaient guère les quatre autres.
C'est alors que le **Cingalais** proposa une partie de pêche en mer.
Et notre équipage hétéroclite de se diriger vers le port de Nâgapattinam.
Un **aconier** **balèze**, vieux **briscard** plein de **bagou**, embarqua tout ce beau monde.
Pas loin du **rouf**, la voile **faseillait** et les **aussières** tremblaient, résistant au **norois**.
Le **maharajah** choisit en guise de **boëte** un **boucaud**, prit une **daurade** et poussa un **hourra**.
Le **guru**, dont l'**esche** était un **cabillaud**, ferra un **béluga**.
Le **muphti** et le **calife** furent surpris de trouver dans leurs **seines**, en pleine mer, un **chevesne** et une **barbote** !  Après avoir **arisé**, ils accostèrent.
Un **canaque** portant un **baluchon** et un **jerrican** les accueillit.
Il était accompagné d'un **bardeau** et d'un **cacatoès** qui grignotait des **cacahuètes**.
Quant au **Cingalais**, tout pêcheur qu'il était, il revint bredouille et dut se contenter au repas d'un **bortsch**, avec un peu d'**aïoli**, d'un **goulache** arrosé d'un verre de **gnôle** frelatée et de quelques **akènes**…

== Orthographe standard — version 2

Ami du **shah**, le **maharadjah**, sitôt sorti de l'**asram**, courut retrouver dans l'arrière-salle d'un **bistrot** le **gourou** et un **mufti** de ses amis.
Étaient aussi présents un **khalife** **iraqien**, de **Baghdad** pour être précis, et un **Cinghalais**, pêcheur à Puttalam et vêtu d'un **shantung** coloré.
Tous conversaient paisiblement autour d'un **narghilé** chargé de **hachich** parfumé à l'huile de coprah.
La curieuse confrérie ne tarda pas à divaguer, non loin de beaux **lys** et jolis bougainvilliers.
Le **mufti**, qui était un grand **sufi**, entama une **surate** et des soutra qui n'amusaient guère les quatre autres.
C'est alors que le **Cinghalais** proposa une partie de pêche en mer.
Et notre équipage hétéroclite de se diriger vers le port de Nâgapattinam.
Un **acconier** **balaise**, vieux **brisquard** plein de **bagout**, embarqua tout ce beau monde.
Pas loin du **roof**, la voile **faséyait**, et les **haussières** tremblaient, résistant au **noroît**.
Le **maharadjah** choisit en guise de **boette** un **boucot**, prit une **dorade** et poussa un **hurra**.
Le **gourou**, dont l'**aiche** était un **cabillau**, ferra un **bélouga**.
Le **mufti** et le **khalife** furent surpris de trouver dans leurs **sennes**, en pleine mer, un **chevaine** et une **barbotte** !  Après avoir **arrisé**, ils accostèrent.
Un **kanak** portant un **balluchon** et un **jerricane** les accueillit.
Il était accompagné d'un **bardot** et d'un **kakatoès** qui grignotait des **cacahouètes**.
Quant au **Cinghalais**, tout pêcheur qu'il était, il revint bredouille et dut se contenter au repas d'un **borchtch**, avec un peu d'**ailloli**, d'un **goulasch** arrosé d'un verre de **gnaule** frelatée et de quelques **achaines**…

== Alphabet Phonétique International — version 1

amˈi dy- ʃˈa
lə- maaʁadʒˈa
sitˈo sɔʁtˈi də- laʃʁˈam
kuʁˈy ʁətʁuvˈe dɑ̃ laʁjˈɛʁsˈal dœ̃ bistʁˈo lə- ɡuʁˈu e œ̃ myftˈi də- se-z amˈi

etˈɛt osˌi pʁezˈɑ̃z œ̃ kalif iʁakjˈɛ̃
də- baɡdˈad puʁ ˈɛtʁ pʁesˈi
e œ̃ sɛ̃ɡalˈɛ
pɛʃˈœʁ a pytalˈam e vɛtˈy dœ̃ ʃɑ̃tuŋ kɔlɔʁˈe

tus kɔ̃vɛʁsˈɛ pɛzibləmˈɑ̃ otˌuʁ dœ̃ naʁɡilˈe ʃaʁʒˈe də- aʃˈiʃ paʁfymˈe a lyˈil də- kɔpʁˈa

la- kyʁjˈøz kɔ̃fʁeʁˈi nə- taʁdˈa paz a divaɡˈe
nɔ̃ lwˌɛ̃ də- bˈo lˈi e ʒɔlˈi buɡɛ̃vijjˈe

lə- myftˈi
ki etˈɛt œ̃ ɡʁˈɑ̃ sufˈi
ɑ̃tamˈa yn suʁˈat e de- sutʁˈa ki namyzˈɛ ɡɛʁ le- kˈatʁ ˈotʁ

sɛt alˌɔʁ kə lə- sɛ̃ɡalˈɛ pʁɔpozˈa yn paʁtˈi də- pˈɛʃ ɑ̃ mˈɛʁ

e nɔtʁ ekipˈaʒ eteʁɔklˈit də- sə- diʁiʒˈe vɛʁ lə- pˈɔʁ də- naɡapatinˈam

œ̃n akɔnjˈe balˈɛz
vjˈø bʁiskˈaʁ plˈɛ̃ də- baɡˈu
ɑ̃baʁkˈa tu sə- bˈo mˈɔ̃d

pa lwˌɛ̃ dy- ʁˈuf
la- vwˈal fazɛjˈɛt
e le-z osjˈɛʁ tʁɑ̃blˈɛ
ʁezistˈɑ̃ o nɔʁwˈa

lə- maaʁadʒˈa ʃwazˈi ɑ̃ ɡˈiz də- bɔˈɛt œ̃ bukˈo
pʁˈi yn doʁˈad e pusˈa œ̃ uʁˈa

lə- ɡuʁˈu
dɔ̃ lˈɛʃ etˈɛt œ̃ kabijˈo
fɛʁˈa œ̃ **belyɡˈa**

lə- myftˈi e lə-kalif fyʁ syʁpʁˈi də- tʁuvˈe dɑ̃ lœʁ sˈɛn
ɑ̃ plˈɛn mˈɛʁ
œ̃ ʃəvˈɛn e yn baʁbˈɔt
apʁˌɛz avwˈaʁ aʁizˈe
ilz akɔstˈɛʁ

œ̃ kanˈak pɔʁtˈɑ̃ œ̃ balyʃˈɔ̃ e œ̃ ʒɛʁikˈan le-z akœjˈi

il etˈɛt akɔ̃panjˈe dœ̃ baʁdˈo e dœ̃ kakatɔˈɛ ki ɡʁinjɔtˈɛ de- kakawˈɛt

kɑ̃t o sɛ̃ɡalˈɛ
tu pɛʃˈœʁ kil etˈɛ
il ʁəvˈɛ̃ bʁədˈuj e dˈy sə- kɔ̃tɑ̃tˈe o ʁəpˈa dœ̃ **bˈɔʁtʃ**
avˌɛk œ̃ pø dajɔlˈi
dœ̃ ɡulˈaʃ aʁozˈe dœ̃ vˈɛʁ də- njˈol fʁəlatˈe e də- kˌɛlkəz akˈɛn

== Alphabet Phonétique International — version 2

amˈi dy- ʃˈa
lə- maaʁadʒˈa
sitˈo sɔʁtˈi də- laʃʁˈam
kuʁˈy ʁətʁuvˈe dɑ̃ laʁjˈɛʁsˈal dœ̃ bistʁˈo lə- ɡuʁˈu e œ̃ myftˈi də- se-z amˈi

etˈɛt osˌi pʁezˈɑ̃z œ̃ kalif iʁakjˈɛ̃
də- baɡdˈad puʁ ˈɛtʁ pʁesˈi
e œ̃ sɛ̃ɡalˈɛ
pɛʃˈœʁ a pytalˈam e vɛtˈy dœ̃ ʃɑ̃tuŋ kɔlɔʁˈe

tus kɔ̃vɛʁsˈɛ pɛzibləmˈɑ̃ otˌuʁ dœ̃ naʁɡilˈe ʃaʁʒˈe də- aʃˈiʃ paʁfymˈe a lyˈil də- kɔpʁˈa

la- kyʁjˈøz kɔ̃fʁeʁˈi nə- taʁdˈa paz a divaɡˈe
nɔ̃ lwˌɛ̃ də- bˈo lˈi e ʒɔlˈi buɡɛ̃vijjˈe

lə- myftˈi
ki etˈɛt œ̃ ɡʁˈɑ̃ sufˈi
ɑ̃tamˈa yn suʁˈat e de- sutʁˈa ki namyzˈɛ ɡɛʁ le- kˈatʁ ˈotʁ

sɛt alˌɔʁ kə lə- sɛ̃ɡalˈɛ pʁɔpozˈa yn paʁtˈi də- pˈɛʃ ɑ̃ mˈɛʁ

e nɔtʁ ekipˈaʒ eteʁɔklˈit də- sə- diʁiʒˈe vɛʁ lə- pˈɔʁ də- naɡapatinˈam

œ̃n akɔnjˈe balˈɛz
vjˈø bʁiskˈaʁ plˈɛ̃ də- baɡˈu
ɑ̃baʁkˈa tu sə- bˈo mˈɔ̃d

pa lwˌɛ̃ dy- ʁˈuf
la- vwˈal fazɛjˈɛt
e le-z osjˈɛʁ tʁɑ̃blˈɛ
ʁezistˈɑ̃ o nɔʁwˈa

lə- maaʁadʒˈa ʃwazˈi ɑ̃ ɡˈiz də- bɔˈɛt œ̃ bukˈo
pʁˈi yn doʁˈad e pusˈa œ̃ uʁˈa

lə- ɡuʁˈu
dɔ̃ lˈɛʃ etˈɛt œ̃ kabijˈo
fɛʁˈa œ̃ **beluɡˈa**

lə- myftˈi e lə-kalif fyʁ syʁpʁˈi də- tʁuvˈe dɑ̃ lœʁ sˈɛn
ɑ̃ plˈɛn mˈɛʁ
œ̃ ʃəvˈɛn e yn baʁbˈɔt
apʁˌɛz avwˈaʁ aʁizˈe
ilz akɔstˈɛʁ

œ̃ kanˈak pɔʁtˈɑ̃ œ̃ balyʃˈɔ̃ e œ̃ ʒɛʁikˈan le-z akœjˈi

il etˈɛt akɔ̃panjˈe dœ̃ baʁdˈo e dœ̃ kakatɔˈɛ ki ɡʁinjɔtˈɛ de- kakawˈɛt

kɑ̃t o sɛ̃ɡalˈɛ
tu pɛʃˈœʁ kil etˈɛ
il ʁəvˈɛ̃ bʁədˈuj e dˈy sə- kɔ̃tɑ̃tˈe o ʁəpˈa dœ̃ **bˈɔʁʃtʃ**
avˌɛk œ̃ pø dajɔlˈi
dœ̃ ɡulˈaʃ aʁozˈe dœ̃ vˈɛʁ də- njˈol fʁəlatˈe e də- kˌɛlkəz akˈɛn

== Akarlãg

Ami du ȼa, le maaradja, sitô sorti de laȼram, kůru retrůvé dã l'aryèr-sal d'ũ
bistrô le gůrů é ũ mufti de sȩ́ ami'.
Étè̝' ôsi prézã' ũ kalif irakyũ, de Bagdad půr ètr prési, é ũ Sĩgalè, pèȼœr a
Putalam é vètu d'ũ ȼãtůŋ koloré.
Tůs kõvèrsè' pèziblemã ôtůr d'ũ nargilé ȼarjé de aȼiȼ parfumé a l'uil de kopra.
La kuryœz kõfréri ne tarda pa̧ a divagé, nõ lwĩ de bô' lis' é joli' bůgĩviyyé'.
Le mufti, ki étèt ũ grã sůfi, ãtama un sůrat é dé' sůtra' ki namuzè' gèr lé'
katr ôtr'.
S'è̝ alor ke le Sĩgalè propôza un parti de pèȼ ã mèr.
É notr ékipaj étéroklit de se dirijé vèr le por de Nagapatinam.
Ṵ̃ akonyé balèz, vyœ briskar plĩ de bagů, ãbarka tů se bô mõd.
Pa lwĩ du růf, la vwal fazėè é lȩ́' ôsyèr' trãblè', rézistã ô norwa.
Le maaradja ȼwazi ã giz de boèt ũ bůkô, pri un dôrad é půsa ũ ůra.
Le gůrů, dõ lèȼ étèt ũ kabiyô, fèra ũ béluga.
Le mufti é le kalif fur' surpri' de trůvé dã lœr' sèn', ã plèn mèr, ũ ȼevèn é un
barbot ! Aprȩ̀ avwar arizé, iļ' akostèr'.
Ũ kanak portã̝ ũ baluȼõ é ũ jèrikan lȩ́ akœyi.
Il étè̝ akõpanyé d'ũ bardô é d'ũ kakatoès ki grinyotè dé' kakawèt'.
Kã̝ ô Sĩgalè, tů pèȼœr k'il étè, il revĩ bredůy é du se kõtãté ô repa d'ũ
bortȼ, avèk ũ pœ d'ȧoli, d'ũ gůlaȼ arôzé d'ũ vèr de nyôl frelaté é de kèlkȩ'
akèn'…

== Akarlahg

Ami du ca, le maaradja, sito sorti de lacram, khuru retrhuveh dah l'aryher-sal
d'uh bistro le ghurhu eh uh mufti de seh" ami'.
EHthe-' osi prehzah' uh kalif irakyuh, de Bagdad phur hetr prehsi, eh uh
Sihgalhe, phecer a Putalam eh vhetu d'uh cahthung koloreh.
Thus kohvhershe' pheziblemah othur d'uh nargileh carjeh de acic parfumeh a l'uil
de kopra.
La kuryez kohfrehri ne tarda pa" a divageh, noh lwih de bo' lis' eh joli'
bhugihviyyeh'.
Le mufti, ki ehthet uh grah shufi, ahtama un shurat eh deh' shutra' ki namuzhe'
gher leh' katr otr'.
S'he- alor ke le Sihgalhe propoza un parti de phec ah mher.
EH notr ehkipaj ehtehroklit de se dirijeh vher le por de Nagapatinam.
UH akonyeh balhez, vye briskar plih de baghu, ahbarka thu se bo mohd.
Pa lwih du rhuf, la vwal fazeyhe eh leh" osyher' trahblhe', rehzistah o norwa.
Le maaradja cwazi ah giz de bohet uh bhuko, pri un dorad eh phusa uh hura.
Le ghurhu, doh lhec ehthet uh kabiyo, fhera uh behluga.
Le mufti eh le kalif fur' surpri' de trhuveh dah ler' shen', ah plhen mher, uh
cevhen eh un barbot ! Aprhe" avwar arizeh, il" akosther'.
UH kanak portah- uh balucoh eh uh jherikan leh" akeyi.
Il ehthe- akohpanyeh d'uh bardo eh d'uh kakatohes ki grinyothe deh' kakawhet'.
Kah- o Sihgalhe, thu phecer k'il ehthe, il revih bredhuy eh du se kohtahteh o
repa d'uh bortc, avhek uh pe d'ayoli, d'uh ghulac arozeh d'uh vher de nyol
frelateh eh de khelke" akhen'…

== Akarlang

Ami du cha, le maharadja, sito sorti de l'achram, couru retrouvé dan
l'arière-sale d'un bistro le gourou et un mufti de ses ami.
Été ossi présan un kalif iraqien, de Bagdad pour ètre préci, et un Cingalai,
pècheur à Puttalam et vêtu d'un chantoung coloré.
Tous conversai paisibleman otour d'un narghilé chargé de hachich parfumé à
l'uile de coprah.
La curieuse confréri ne tarda pas à divagué, non loin de bo lis et joli
bouginvilié.
Le mufti, qui été un gran soufi, entama une sourate et des soutra qui n'amusai
guère les catre otre.
C'est alor que le Cingalai proposa une parti de pèche en mer.
Et notre éqipage étéroclite de se dirigé ver le por de Nâgapattinam.
Un aconié balèze, vieu briscar plin de bagou, enbarca tou ce bo monde.
Pas loin du rouf, la voile faséyai, et les ossière trenblai, résistan au noroi.
Le maharadja choisi en guise de boète un bouco, pri une dorade et poussa un
houra.
Le gourou, don l'èche étai un cabiyo, féra un bélouga.
Le mufti et le kalif fure surpri de trouvé dans leur sène, en plène mer, un
chevène et une barbote ! Aprè avoir arisé, ils acostère.
Un kanak portan un baluchon et un jericane les aqeuyi.
Il été aconpagné d'un bardo et d'un kakatoès qui grignotai des cacaouète.
Quant au Cingalai, tout pècheur qu'il été, il revin bredouye et du se contenté
au repa d'un borchtch, avec un peu d'ayoli, d'un goulach arosé d'un ver de gnôle
frelaté et de quelques achène…
