= Le Maharadjah est l'ami du Shah

> Que les lecteurs fâchés avec l'orthographe se rassurent, car, même si les
dictionnaires semblent rarement d'accord, toutes ces graphies sont possibles. Et
bien d'autres mots peuvent s'orthographier de deux façons. D'où les deux dictées
suivantes, aussi recevables l'une que l'autre.

Extrait du « Dictionnaire amoureux de la Langue française » de Jean-Loup Chiflet

== Orthographe standard — version 1

Ami du **chah**, le **maharajah**, sitôt sorti de l'**ashram**, courut retrouver dans l'arrière-salle d'un **bistro** le **guru** et un **muphti** de ses amis.
Étaient aussi présents un **calife** **irakien**, de **Bagdad** pour être précis, et un **Cingalais**, pêcheur à Puttalam et vêtu d'un **chantoung** coloré.
Tous conversaient paisiblement autour d'un **narguilé** chargé de **haschisch** parfumé à l'huile de coprah.
La curieuse confrérie ne tarda pas à divaguer, non loin de beaux **lis** et jolis bougainvilliers.
Le **muphti**, qui était un grand **soufi**, entama une **sourate** et des soutra qui n'amusaient guère les quatre autres.
C'est alors que le **Cingalais** proposa une partie de pêche en mer.
Et notre équipage hétéroclite de se diriger vers le port de Nâgapattinam.
Un **aconier** **balèze**, vieux **briscard** plein de **bagou**, embarqua tout ce beau monde.
Pas loin du **rouf**, la voile **faseillait** et les **aussières** tremblaient, résistant au **norois**.
Le **maharajah** choisit en guise de **boëte** un **boucaud**, prit une **daurade** et poussa un **hourra**.
Le **guru**, dont l'**esche** était un **cabillaud**, ferra un **béluga**.
Le **muphti** et le **calife** furent surpris de trouver dans leurs **seines**, en pleine mer, un **chevesne** et une **barbote** !  Après avoir **arisé**, ils accostèrent.
Un **canaque** portant un **baluchon** et un **jerrican** les accueillit.
Il était accompagné d'un **bardeau** et d'un **cacatoès** qui grignotait des **cacahuètes**.
Quant au **Cingalais**, tout pêcheur qu'il était, il revint bredouille et dut se contenter au repas d'un **bortsch**, avec un peu d'**aïoli**, d'un **goulache** arrosé d'un verre de **gnôle** frelatée et de quelques **akènes**…

== Orthographe standard — version 2

Ami du **shah**, le **maharadjah**, sitôt sorti de l'**asram**, courut retrouver dans l'arrière-salle d'un **bistrot** le **gourou** et un **mufti** de ses amis.
Étaient aussi présents un **khalife** **iraqien**, de **Baghdad** pour être précis, et un **Cinghalais**, pêcheur à Puttalam et vêtu d'un **shantung** coloré.
Tous conversaient paisiblement autour d'un **narghilé** chargé de **hachich** parfumé à l'huile de coprah.
La curieuse confrérie ne tarda pas à divaguer, non loin de beaux **lys** et jolis bougainvilliers.
Le **mufti**, qui était un grand **sufi**, entama une **surate** et des soutra qui n'amusaient guère les quatre autres.
C'est alors que le **Cinghalais** proposa une partie de pêche en mer.
Et notre équipage hétéroclite de se diriger vers le port de Nâgapattinam.
Un **acconier** **balaise**, vieux **brisquard** plein de **bagout**, embarqua tout ce beau monde.
Pas loin du **roof**, la voile **faséyait**, et les *$haussières$* tremblaient, résistant au *$noroît$*.
Le **maharadjah** choisit en guise de **boette** un **boucot**, prit une **dorade** et poussa un **hurra**.
Le **gourou**, dont l'**aiche** était un **cabillau**, ferra un **bélouga**.
Le **mufti** et le **khalife** furent surpris de trouver dans leurs **sennes**, en pleine mer, un **chevaine** et une **barbotte** !  Après avoir **arrisé**, ils accostèrent.
Un **kanak** portant un **balluchon** et un **jerricane** les accueillit.
Il était accompagné d'un **bardot** et d'un **kakatoès** qui grignotait des **cacahouètes**.
Quant au **Cinghalais**, tout pêcheur qu'il était, il revint bredouille et dut se contenter au repas d'un **borchtch**, avec un peu d'**ailloli**, d'un **goulasch** arrosé d'un verre de **gnaule** frelatée et de quelques **achaines**…

== Alphabet Phonétique International — version 1

amˈi dy- ʃˈa
lə- maaʁadʒˈa
sitˈo sɔʁtˈi də- laʃʁˈam
kuʁˈy ʁətʁuvˈe dɑ̃ laʁjˈɛʁsˈal dœ̃ bistʁˈo lə- ɡuʁˈu e œ̃ myftˈi də- se-z amˈi

etˈɛt osˌi pʁezˈɑ̃z œ̃ kalif iʁakjˈɛ̃
də- baɡdˈad puʁ ˈɛtʁ pʁesˈi
e œ̃ sɛ̃ɡalˈɛ
pɛʃˈœʁ a pytalˈam e vɛtˈy dœ̃ ʃɑ̃tuŋ kɔlɔʁˈe

tus kɔ̃vɛʁsˈɛ pɛzibləmˈɑ̃ otˌuʁ dœ̃ naʁɡilˈe ʃaʁʒˈe də- aʃˈiʃ paʁfymˈe a lyˈil də- kɔpʁˈa

la- kyʁjˈøz kɔ̃fʁeʁˈi nə- taʁdˈa paz a divaɡˈe
nɔ̃ lwˌɛ̃ də- bˈo lˈi e ʒɔlˈi buɡɛ̃vijjˈe

lə- myftˈi
ki etˈɛt œ̃ ɡʁˈɑ̃ sufˈi
ɑ̃tamˈa yn suʁˈat e de- sutʁˈa ki namyzˈɛ ɡɛʁ le- kˈatʁ ˈotʁ

sɛt alˌɔʁ kə lə- sɛ̃ɡalˈɛ pʁɔpozˈa yn paʁtˈi də- pˈɛʃ ɑ̃ mˈɛʁ

e nɔtʁ ekipˈaʒ eteʁɔklˈit də- sə- diʁiʒˈe vɛʁ lə- pˈɔʁ də- naɡapatinˈam

œ̃n akɔnjˈe balˈɛz
vjˈø bʁiskˈaʁ plˈɛ̃ də- baɡˈu
ɑ̃baʁkˈa tu sə- bˈo mˈɔ̃d

pa lwˌɛ̃ dy- ʁˈuf
la- vwˈal fazɛjˈɛt
e le-z osjˈɛʁ tʁɑ̃blˈɛ
ʁezistˈɑ̃ o nɔʁwˈa

lə- maaʁadʒˈa ʃwazˈi ɑ̃ ɡˈiz də- bɔˈɛt œ̃ bukˈo
pʁˈi yn doʁˈad e pusˈa œ̃ uʁˈa

lə- ɡuʁˈu
dɔ̃ lˈɛʃ etˈɛt œ̃ kabijˈo
fɛʁˈa œ̃ **belyɡˈa**

lə- myftˈi e lə-kalif fyʁ syʁpʁˈi də- tʁuvˈe dɑ̃ lœʁ sˈɛn
ɑ̃ plˈɛn mˈɛʁ
œ̃ ʃəvˈɛn e yn baʁbˈɔt
apʁˌɛz avwˈaʁ aʁizˈe
ilz akɔstˈɛʁ

œ̃ kanˈak pɔʁtˈɑ̃ œ̃ balyʃˈɔ̃ e œ̃ ʒɛʁikˈan le-z akœjˈi

il etˈɛt akɔ̃panjˈe dœ̃ baʁdˈo e dœ̃ kakatɔˈɛ ki ɡʁinjɔtˈɛ de- kakawˈɛt

kɑ̃t o sɛ̃ɡalˈɛ
tu pɛʃˈœʁ kil etˈɛ
il ʁəvˈɛ̃ bʁədˈuj e dˈy sə- kɔ̃tɑ̃tˈe o ʁəpˈa dœ̃ **bˈɔʁtʃ**
avˌɛk œ̃ pø dajɔlˈi
dœ̃ ɡulˈaʃ aʁozˈe dœ̃ vˈɛʁ də- njˈol fʁəlatˈe e də- kˌɛlkəz akˈɛn

== Alphabet Phonétique International — version 2

amˈi dy- ʃˈa
lə- maaʁadʒˈa
sitˈo sɔʁtˈi də- laʃʁˈam
kuʁˈy ʁətʁuvˈe dɑ̃ laʁjˈɛʁsˈal dœ̃ bistʁˈo lə- ɡuʁˈu e œ̃ myftˈi də- se-z amˈi

etˈɛt osˌi pʁezˈɑ̃z œ̃ kalif iʁakjˈɛ̃
də- baɡdˈad puʁ ˈɛtʁ pʁesˈi
e œ̃ sɛ̃ɡalˈɛ
pɛʃˈœʁ a pytalˈam e vɛtˈy dœ̃ ʃɑ̃tuŋ kɔlɔʁˈe

tus kɔ̃vɛʁsˈɛ pɛzibləmˈɑ̃ otˌuʁ dœ̃ naʁɡilˈe ʃaʁʒˈe də- aʃˈiʃ paʁfymˈe a lyˈil də- kɔpʁˈa

la- kyʁjˈøz kɔ̃fʁeʁˈi nə- taʁdˈa paz a divaɡˈe
nɔ̃ lwˌɛ̃ də- bˈo lˈi e ʒɔlˈi buɡɛ̃vijjˈe

lə- myftˈi
ki etˈɛt œ̃ ɡʁˈɑ̃ sufˈi
ɑ̃tamˈa yn suʁˈat e de- sutʁˈa ki namyzˈɛ ɡɛʁ le- kˈatʁ ˈotʁ

sɛt alˌɔʁ kə lə- sɛ̃ɡalˈɛ pʁɔpozˈa yn paʁtˈi də- pˈɛʃ ɑ̃ mˈɛʁ

e nɔtʁ ekipˈaʒ eteʁɔklˈit də- sə- diʁiʒˈe vɛʁ lə- pˈɔʁ də- naɡapatinˈam

œ̃n akɔnjˈe balˈɛz
vjˈø bʁiskˈaʁ plˈɛ̃ də- baɡˈu
ɑ̃baʁkˈa tu sə- bˈo mˈɔ̃d

pa lwˌɛ̃ dy- ʁˈuf
la- vwˈal fazɛjˈɛt
e le-z osjˈɛʁ tʁɑ̃blˈɛ
ʁezistˈɑ̃ o nɔʁwˈa

lə- maaʁadʒˈa ʃwazˈi ɑ̃ ɡˈiz də- bɔˈɛt œ̃ bukˈo
pʁˈi yn doʁˈad e pusˈa œ̃ uʁˈa

lə- ɡuʁˈu
dɔ̃ lˈɛʃ etˈɛt œ̃ kabijˈo
fɛʁˈa œ̃ **beluɡˈa**

lə- myftˈi e lə-kalif fyʁ syʁpʁˈi də- tʁuvˈe dɑ̃ lœʁ sˈɛn
ɑ̃ plˈɛn mˈɛʁ
œ̃ ʃəvˈɛn e yn baʁbˈɔt
apʁˌɛz avwˈaʁ aʁizˈe
ilz akɔstˈɛʁ

œ̃ kanˈak pɔʁtˈɑ̃ œ̃ balyʃˈɔ̃ e œ̃ ʒɛʁikˈan le-z akœjˈi

il etˈɛt akɔ̃panjˈe dœ̃ baʁdˈo e dœ̃ kakatɔˈɛ ki ɡʁinjɔtˈɛ de- kakawˈɛt

kɑ̃t o sɛ̃ɡalˈɛ
tu pɛʃˈœʁ kil etˈɛ
il ʁəvˈɛ̃ bʁədˈuj e dˈy sə- kɔ̃tɑ̃tˈe o ʁəpˈa dœ̃ **bˈɔʁʃtʃ**
avˌɛk œ̃ pø dajɔlˈi
dœ̃ ɡulˈaʃ aʁozˈe dœ̃ vˈɛʁ də- njˈol fʁəlatˈe e də- kˌɛlkəz akˈɛn
